name: CSS Lint

on: [push, pull_request]

jobs:
  linters:
    name: stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions-hub/stylelint@master
        env:
          INDENT_SPACES: 2
          PATTERN: "library/css/*.css"