name: WPCS check

on: [push, pull_request]

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Action
          uses: actions/checkout@v3

        - name: WPCS Check
          uses: 10up/wpcs-action@stable
          with:
            paths: '.'
          
paths-ignore:
  - 'wordpress-block-react/*/*'
  - 'wordpress-block-vanillajs/*/*'
  - 'CMB2/*'