name: WPCS check

on: [push, pull_request]

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: WPCS check
          uses: 10up/wpcs-action@stable
          with:
            path-ignore: |
              wordpress-block-react/
              CMB2/