name: Your Workflow Name
on:
  push:
    branches:
      - main

jobs:
  wpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run WPCS
        uses: 10up/wpcs-action@master
        with:
          ignore: 'wordpress-block-react/*,CMB2/*,CMB2/*/*